# Generated by Django 5.2.8 on 2025-11-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
