# Generated by Django 5.2.8 on 2025-11-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad en stock')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
